# Generated by Django 6.0 on 2025-12-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.TextField()),
                ('machine_id', models.TextField(null=True)),
                ('license_key', models.TextField(null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_id', models.TextField(unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_key', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='myapp.machine', to_field='machine_id')),
            ],
        ),
    ]
