# Generated by Django 5.0.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=64)),
                ('machine_id', models.CharField(blank=True, max_length=64, null=True)),
                ('license_key', models.CharField(blank=True, max_length=128, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(max_length=256)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='myapp.machine')),
            ],
        ),
    ]
